//
// Created by Антон on 17.06.2021.
//

#ifndef TIMES_AND_PLANES_2021_06_CALCULATE_TS_FOR_EADGES_OF_CONSTRICTED_ZONE_H
#define TIMES_AND_PLANES_2021_06_CALCULATE_TS_FOR_EADGES_OF_CONSTRICTED_ZONE_H


#include <Zone.h>

void calc_TS_edges_of_constricted_zone(Zone &zone);

#endif //TIMES_AND_PLANES_2021_06_CALCULATE_TS_FOR_EADGES_OF_CONSTRICTED_ZONE_H
